# copied from https://github.com/timtroendle/possibility-for-electricity-autarky/blob/master/rules/data-preprocessing.smk
snakemake:
    max-threads: 4
crs: "EPSG:4326"
scope:
    countries:
        - "Austria"
        - "Belgium"
        - "Bulgaria"
        - "Croatia"
        - "Cyprus"
        - "Czech Republic"
        - "Denmark"
        - "Estonia"
        - "Finland"
        - "France"
        - "Germany"
        - "Greece"
        - "Hungary"
        - "Ireland"
        - "Italy"
        - "Latvia"
        - "Lithuania"
        - "Luxembourg"
        - "Netherlands"
        - "Poland"
        - "Portugal"
        - "Romania"
        - "Slovakia"
        - "Slovenia"
        - "Spain"
        - "Sweden"
        - "United Kingdom"
        - "Albania"
        - "Bosnia and Herzegovina"
        - "Macedonia, Republic of"
        - "Montenegro"
        - "Norway"
        - "Serbia"
        - "Switzerland"
    bounds:
        x_min: -10
        x_max: 2
        y_min: 49
        y_max: 61